SDI_Gestion/Models/Solicitud.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SDI_Gestion.Models
{
    public class Solicitud
    {
        public decimal id_Solicitud { get; set; }
        public DateTime fch_Ingreso { get; set; }
        [Required(ErrorMessage = "Este campo es requerido.")]
        public string asunto_Sol { get; set; }
        [Required(ErrorMessage = "Este campo es requerido.")]
        public string detalle_Sol { get; set; }
        [Required(ErrorMessage = "Este campo es requerido.")]
        public decimal id_Area { get; set; }
        public decimal id_Usuario { get; set; }
        [Required(ErrorMessage = "Este campo es requerido.")]
        public decimal id_Prioridad { get; set; }
        public string cod_Estado_Sol { get; set; }

        public decimal id_Tipo_Sol { get; set; }

        public DateTime fch_Estado_Sol { get; set; }

        public Usuario usuario_Solicitud { get; set; }

        public Prioridad prioridad_Solicitud { get; set; }

        public EstadoSolicitud estado_Solicitud { get; set; }

        public TipoSolicitud tipo_Solicitud { get; set; }

        public List<Movimiento> movimientos_Solicitud { get; set; }

        public ListasSolicitud ListasSolicitud { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}

SDI_Gestion/Controllers/Solicitud/SolicitudController.cs
using Newtonsoft.Json;
using SDI_Gestion.Models;
using SDI_Gestion.Utility;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SDI_Gestion.Controllers.Solicitud
{
    public class SolicitudController : BaseController
    {
        List<Object> myModel = new List<object>();
        Usuario usuarioMail = new Usuario();

        // GET: Solicitud
        public async Task<ActionResult> Index()
        {
            //LLAMADAS A LA API
            List<TipoSolicitud> tiposSolicitud = new List<TipoSolicitud>();

            var httpClient = new HttpClient();
            SDI_Gestion.Models.Solicitud solicitud = new SDI_Gestion.Models.Solicitud();

            //rescatamos las areas
            var json = await httpClient.GetStringAsync(Resource.AreaAPIUrl);
            List<Area> areas = JsonConvert.DeserializeObject<List<Area>>(json);

            //rescatamos las prioridades 
            json = await httpClient.GetStringAsync(Resource.PrioridadAPIUrl);
            List<Prioridad> prioridades = JsonConvert.DeserializeObject<List<Prioridad>>(json);

            //Rescatamos el usuario que esta conectado
            json = await httpClient.GetStringAsync(Resource.UsuarioMailAPIUrl + Session["user_Email"].ToString().Trim());
            Usuario usuario = JsonConvert.DeserializeObject<Usuario>(json);

            solicitud.usuario_Solicitud = usuario;
            solicitud.ListasSolicitud = new ListasSolicitud();
            solicitud.ListasSolicitud.Areas = areas;
            solicitud.ListasSolicitud.Prioridades = prioridades;
            solicitud.ListasSolicitud.TiposSolicitud = tiposSolicitud;


            myModel.Add(solicitud);
            ViewBag.Message2 = "Ingreso";
            return View(myModel);
        }

        [HttpPost]
        public Task<string> BuscarTiposSolicitudArea(int idArea)
        {
            var httpClient = new HttpClient();
            var tiposSolicitud = httpClient.GetStringAsync(Resource.TipoSolicitudAreaAPIUrl + idArea);
            return tiposSolicitud;
        }

        // GET: Solicitud
        [HttpGet]
        public async Task<ActionResult> CargarSolicitud(decimal id_Solicitud)
        {
            //LLAMADAS A LA API
            var httpClient = new HttpClient();
            SDI_Gestion.Models.Solicitud solicitud = new SDI_Gestion.Models.Solicitud();

            //rescatamos las areas
            var json = await httpClient.GetStringAsync(Resource.AreaAPIUrl);
            List<Area> areas = JsonConvert.DeserializeObject<List<Area>>(json);

            //rescatamos las prioridades 
            json = await httpClient.GetStringAsync(Resource.PrioridadAPIUrl);
            List<Prioridad> prioridades = JsonConvert.DeserializeObject<List<Prioridad>>(json);

            //Rescatamos los datos de la solicitud
            json = await httpClient.GetStringAsync(Resource.SolicitudAPIUrl + id_Solicitud);
            solicitud = JsonConvert.DeserializeObject<SDI_Gestion.Models.Solicitud>(json);

            //Cargamos tipos de solicitud degun el área que tiene la solicitud
            json = await httpClient.GetStringAsync(Resource.TipoSolicitudAreaAPIUrl + solicitud.id_Area);
            List<TipoSolicitud> tiposSolicitud = JsonConvert.DeserializeObject<List<TipoSolicitud>>(json);


            //Rescatamos el usuario que esta conectado
            json = await httpClient.GetStringAsync(Resource.UsuarioMailAPIUrl + Session["user_Email"].ToString().Trim());
            Usuario usuario = JsonConvert.DeserializeObject<Usuario>(json);

            solicitud.usuario_Solicitud = usuario;
            solicitud.ListasSolicitud = new ListasSolicitud();
            solicitud.ListasSolicitud.Areas = areas;
            solicitud.ListasSolicitud.Prioridades = prioridades;
            solicitud.ListasSolicitud.TiposSolicitud = tiposSolicitud;

            myModel.Add(solicitud);

            return View(myModel);
        }

        // GET: Solicitud
        [HttpGet]
        public async Task<ActionResult> Toma()
        {
            var httpClient = new HttpClient();
            EstadoSolicitudMovimiento estadoMovimiento = new EstadoSolicitudMovimiento();
            List<SDI_Gestion.Models.Solicitud> solicitudes = new List<SDI_Gestion.Models.Solicitud>();
            SDI_Gestion.Models.Solicitud solicitudAsigna = new SDI_Gestion.Models.Solicitud();

            //Rescatamos el usuario que esta conectado
            var json = await httpClient.GetStringAsync(Resource.UsuarioMailAPIUrl + Session["user_Email"].ToString().Trim());
            Usuario usuario = JsonConvert.DeserializeObject<Usuario>(json);

            decimal id_Area = usuario.id_Area;


            //Rescatamos las solicitudes que estan asociadas al area y que estan en estado de ingresadas (ING)
            //Rescatamos los datos de la solicitud
            json = await httpClient.GetStringAsync(Resource.SolicitudIngAreaAPIUrl + id_Area);
            solicitudes = JsonConvert.DeserializeObject<List<SDI_Gestion.Models.Solicitud>>(json);

            myModel.Add(solicitudes);
            myModel.Add(estadoMovimiento);
            myModel.Add(solicitudAsigna);
            ViewBag.Message2 = "Tomar";
            return View(myModel);
        }

        // GET: Solicitud
        [HttpGet]
        public async Task<ActionResult> Asignacion()
        {
            var httpClient = new HttpClient();
            EstadoSolicitudMovimiento estadoMovimiento = new EstadoSolicitudMovimiento();
            List<SDI_Gestion.Models.Solicitud> solicitudes = new List<SDI_Gestion.Models.Solicitud>();
            List<SDI_Gestion.Models.Usuario> usuarios = new List<SDI_Gestion.Models.Usuario>();
            SDI_Gestion.Models.Solicitud solicitudAsigna = new SDI_Gestion.Models.Solicitud();

            //Rescatamos el usuario que esta conectado
            var json = await httpClient.GetStringAsync(Resource.UsuarioMailAPIUrl + Session["user_Email"].ToString().Trim());
            Usuario usuario = JsonConvert.DeserializeObject<Usuario>(json);

            decimal id_Area = usuario.id_Area;


            //Rescatamos las solicitudes que estan asociadas al area y que estan en estado de ingresadas (ING)
            //Rescatamos los datos de la solicitud
            json = await httpClient.GetStringAsync(Resource.SolicitudIngAreaAPIUrl + id_Area);
            solicitudes = JsonConvert.DeserializeObject<List<SDI_Gestion.Models.Solicitud>>(json);


            //Rescatamos los usuarios del área del perfil conectado
            json = await httpClient.GetStringAsync(Resource.UsuarioAreaAPIUrl + id_Area);
            usuarios = JsonConvert.DeserializeObject<List<SDI_Gestion.Models.Usuario>>(json);


            myModel.Add(solicitudes);
            myModel.Add(estadoMovimiento);
            myModel.Add(solicitudAsigna);
            myModel.Add(usuarios);
            ViewBag.Message2 = "Asignar";
            return View(myModel);
        }

        [HttpPost]
        public async Task<ActionResult> Ingreso(SDI_Gestion.Models.Solicitud solicitud, SDI_Gestion.Models.Archivo archivo)
        {
            var httpClient = new HttpClient();
            HttpStatusCode codigo;
            DateTime fechaActual = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, DateTime.Now.Hour, DateTime.Now.Minute, DateTime.Now.Second, 0);
            HttpResponseMessage respuesta;

            Movimiento movimiento = new Movimiento();

            //Datos Solicitud
            solicitud.fch_Ingreso = fechaActual;
            solicitud.fch_Estado_Sol = fechaActual;
            solicitud.id_Usuario = solicitud.usuario_Solicitud.id_Usuario;
            solicitud.cod_Estado_Sol = "ING";
            //GENERAMOS LA SOLCITUD
            respuesta = await httpClient.PostAsJsonAsync(Resource.SolicitudAPIUrl, solicitud);
            codigo = respuesta.StatusCode;
            Uri urlCotizacion = respuesta.Headers.Location;

            var json = await httpClient.GetStringAsync(urlCotizacion);
            SDI_Gestion.Models.Solicitud solicitudSalida = JsonConvert.DeserializeObject<SDI_Gestion.Models.Solicitud>(json);

            //GENEREAMOS EL ESTADO ASOCIADO AL INGRESO
            movimiento.id_Solicitud = solicitudSalida.id_Solicitud;
            movimiento.id_Usuario = solicitud.id_Usuario;
            movimiento.fch_Movimiento = fechaActual;
            movimiento.horas_Dedicadas = 0;
            movimiento.cod_Estado_Sol = "ING";
            movimiento.observacion = "Ingreso de Solicitud";
            respuesta = await httpClient.PostAsJsonAsync(Resource.MovimientoAPIUrl, movimiento);
            codigo = respuesta.StatusCode;

            Movimiento movimientoGenerado = JsonConvert.DeserializeObject<SDI_Gestion.Models.Movimiento>(await respuesta.Content.ReadAsStringAsync());

            //Enviamos el documento
            if (!(archivo.ImageFile == null))
            {
                Documento documento = new Documento();

                string evidencia;
                string extension = Path.GetExtension(archivo.ImageFile.FileName);
                string formato = (archivo.ImageFile.ContentType);
                string nombreArchivo = Path.GetFileNameWithoutExtension(archivo.ImageFile.FileName);
                using (var binaryreader = new BinaryReader(archivo.ImageFile.InputStream))
                {
                    evidencia = Convert.ToBase64String(binaryreader.ReadBytes(archivo.ImageFile.ContentLength));
                }
                documento.idMovimiento = movimientoGenerado.id_Movimiento;
                documento.extencion = extension;
                documento.evidencia = evidencia;
                documento.formato = formato;
                documento.nombreDocumento = nombreArchivo;
                respuesta = await httpClient.PostAsJsonAsync(Resource.DocumentoAPIUrl, documento);

SDI_Gestion/Views/Solicitud/Asignacion.cshtml
@using SDI_Gestion.Models
@model IEnumerable<Object>
@{
    List<SDI_Gestion.Models.Solicitud> solicitudes = Model.ToArray()[0] as List<SDI_Gestion.Models.Solicitud>;
    EstadoSolicitudMovimiento estadoSolicitudMovimiento = Model.ToArray()[1] as EstadoSolicitudMovimiento;

    SDI_Gestion.Models.Solicitud solicitud = Model.ToArray()[2] as SDI_Gestion.Models.Solicitud;

    List<SDI_Gestion.Models.Usuario> usuarios = Model.ToArray()[3] as List<SDI_Gestion.Models.Usuario>;

    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<link rel="stylesheet" href="~/css/select2-bootstrap4.min.css" type="text/css">
<link rel="stylesheet" href="~/css/select2.min.css" type="text/css">
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

<link rel="stylesheet" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css">
<script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
<script src="~/js/select2.min.js"></script>

<script>

    setTimeout(function () {
        $(".content").fadeOut(1500);
    }, 3000);

    $(document).ready(function () {
        $('#grilla_solicitudes').DataTable(
            {
                "language": {
                    "lengthMenu": "Mostrar _MENU_ registros por página",
                    "zeroRecords": "Sin información",
                    "info": "Mostrando página _PAGE_ de _PAGES_",
                    "infoEmpty": "Sin información disponible",
                    "infoFiltered": "(filtered from _MAX_ total records)"
                }
            }
        );

        $('#asignacion').on('show.bs.modal', function (e) {
            var id = $(e.relatedTarget).data().id;

            var modal = @Html.Raw(Json.Encode(solicitudes));


            for (var i in modal) {
                if (id == modal[i].id_Solicitud) {
                    document.getElementById('solicitud_id_Solicitud').value = modal[i].id_Solicitud;
                    document.getElementById('solicitudMovimiento').innerHTML = modal[i].id_Solicitud;
                    document.getElementById('solicitudMovimientoAsunto').innerHTML = modal[i].asunto_Sol;
                    document.getElementById('solicitudMovimientoDetalle').innerHTML = modal[i].detalle_Sol;
                }
            };
        });
    });

</script>


<div class="container-fluid px-0">
    <div class="card shadow">
        <div class="card-body">

            <div class="row">

                <div class="col-12 mt-3 text-center">

                    <h3>Listado de solicitudes pendientes de asignacion de su área<span class="text-primary"></span></h3>

                </div>

            </div>

            @if (TempData["Mensaje"] != null)
            {
                <div class="row">

                    <div class="col-12 mt-3 text-center">
                        <div class="content" role="alert" aria-live="assertive" aria-atomic="true">
                            <div class="alert alert-success">
                                <button type="button" class="close" data-dismiss="toast" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                @TempData["Mensaje"].ToString()
                            </div>
                        </div>
                    </div>

                </div>
            }

            <div class="tab-pane fade show active" id="home" role="tabpanel"
                 aria-labelledby="home-tab">
                <hr>
                <div class="card-body px-0">
                    <div class="row">
                        <div class="col-12 mt-3">
                            <table id="grilla_solicitudes" class="table table-bordered text-dark table-hover">
                                <thead class="thead-light">
                                    <tr>
                                        <th style="width:20px; text-align:center;">N° Solicitud</th>
                                        <th style="width:100px; text-align:center;">Usuario Solicita</th>
                                        <th style="width:50px; text-align:center;">Fecha Ingreso</th>
                                        <th style="width:50px; text-align:center;">Tipo Solicitud</th>
                                        <th style="width:20px; text-align:center;">Prioridad</th>
                                        <th style="width:170px; text-align:center;">Asunto</th>
                                        <th style="width:70px; text-align:center;">Acción</th>
                                    </tr>
                                </thead>
                                <tbody class="table-sm">
                                    @foreach (var sol in solicitudes)
                                    {
                                        <tr>
                                            <td style="width:20px; text-align:right;">@sol.id_Solicitud</td>
                                            <td>@sol.usuario_Solicitud.nombre_Usr</td>
                                            <td style="text-align: center">@sol.fch_Ingreso.ToString("dd-MM-yyyy hh:mm")</td>
                                            <td style="text-align: left">
                                                @sol.tipo_Solicitud.descripcion


                                                @if (sol.id_Prioridad.Equals(1))
                                                {
                                                <td class="bg-danger text-white text-center" style="width: 20px;">@sol.prioridad_Solicitud.dsc_Prioridad</td>
                                            }
                                            else if (sol.id_Prioridad.Equals(2))
                                            {
                                                <td class="bg-warning text-white text-center" style="width: 20px;">@sol.prioridad_Solicitud.dsc_Prioridad</td>
                                            }
                                            else
                                            {
                                                <td class="bg-success text-white text-center" style="width: 20px;">@sol.prioridad_Solicitud.dsc_Prioridad</td>
                                            }
                                                @*<td>@solicitud.asunto_Sol</td>*@
                                                <td>@sol.detalle_Sol</td>
                                                <th style="text-align: center;">
                                                    <a href="#" id="asigna" data-nombre="@sol.usuario_Solicitud.nombre_Usr" data-id="@sol.id_Solicitud" data-toggle="modal" data-target="#asignacion">
                                                        Asignar Solicitud
                                                    </a>
                                                </th>
                                            </tr>
                                        }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<!-- ASIGNACION DE SOLICITUD -->
<div class="modal fade" id="asignacion" tabindex="-1" role="dialog" style="display: none;"
     aria-hidden="true">
    @using (Html.BeginForm("Asignacion", "Solicitud", null, FormMethod.Post, null))
    {

        @Html.HiddenFor(Model => solicitud.id_Solicitud)

        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModal3Label">Asignacion de Solicitud Número <label id="solicitudMovimiento"></label> </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-12">
                            <form>
                                <div class="form-group">
                                    <b><label for="nombre">Asunto:</label></b>
                                    <label id="solicitudMovimientoAsunto"></label>
                                </div>
                                <div class="form-group">
                                    <b><label for="apellido">Detalle:</label></b>
                                    <label id="solicitudMovimientoDetalle"></label>
                                </div>
                                <div class="form-group">
                                    <b><label for="apellido">Recurso:</label></b>
                                    @Html.DropDownListFor(x => estadoSolicitudMovimiento.id_Usuario,
                                    new SelectList(usuarios, "id_Usuario", "nombre_Usr"),
                                    "Seleccione Usuario", new { @class = "form-control w-100" })
                                </div>
                                <div class="form-group">
                                    <b><label for="email">Observación Asignación:</label></b>
                                    @Html.TextBoxFor(Model => estadoSolicitudMovimiento.observacion, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(Model => estadoSolicitudMovimiento.observacion, null, new { @class = "text-danger" })
                                </div>
                            </form>
                        </div>

                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Asignar Solicitud</button>
                </div>
            </div>
        </div>
    }
</div>

<script type="text/javascript">
    $(function () {
        $('select').each(function () {
            $(this).select2({
                theme: 'bootstrap4',
                width: $(this).data('width') ? $(this).data('width') : $(this).hasClass('w-100') ? '100%' : 'style',
                placeholder: $(this).data('placeholder'),
                allowClear: Boolean($(this).data('allow-clear')),
                closeOnSelect: !$(this).attr('multiple'),
            });
        });
    });
</script>

SDI_Gestion/Views/Solicitud/CargarSolicitud.cshtml
@using SDI_Gestion.Models
@model IEnumerable<Object>
@{
    SDI_Gestion.Models.Solicitud solicitud = Model.ToArray()[0] as SDI_Gestion.Models.Solicitud;

    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<link rel="stylesheet" href="~/css/select2-bootstrap4.min.css" type="text/css">
<link rel="stylesheet" href="~/css/select2.min.css" type="text/css">
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

<link rel="stylesheet" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css">
<script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
<script src="~/js/select2.min.js"></script>

<script>

    setTimeout(function () {
        $(".content").fadeOut(1500);
    }, 3000);

</script>

@using (Html.BeginForm("Modifica", "Solicitud", null, FormMethod.Post, null))
{
    <input type="hidden" id="comunaCliente" value="" />


    @Html.HiddenFor(Model => solicitud.id_Usuario)
    @Html.HiddenFor(Model => solicitud.id_Solicitud)
    @Html.HiddenFor(Model => solicitud.fch_Estado_Sol)
    @Html.HiddenFor(Model => solicitud.fch_Ingreso)
    @Html.HiddenFor(Model => solicitud.cod_Estado_Sol)

    <div class="row">

        <div class="col-md-4 mt-4 mb-2">
            @if (solicitud.id_Solicitud == 0)
            {
                <h2>Solicitud <span class="text-primary">Número ------</span></h2>
            }
            else
            {
                <h2>Solicitud <span class="text-primary">Número @solicitud.id_Solicitud</span></h2>
            }
        </div>
    </div>

    if (TempData["Mensaje"] != null)
    {
        <div class="row">

            <div class="col-12 mt-3 text-center">
                <div class="content" role="alert" aria-live="assertive" aria-atomic="true">
                    <div class="alert alert-success">
                        <button type="button" class="close" data-dismiss="toast" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        @TempData["Mensaje"].ToString()
                    </div>
                </div>
            </div>

        </div>
    }


    <div class="tab-pane fade show active" id="home" role="tabpanel"
         aria-labelledby="home-tab">
        <hr>
        <div class="card-body px-0">
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="mb-0" for="RUT">FECHA REGISTRO</label>
                        <br />
                        <input type="text" id="fechaRegistro" value="AUTOMATICA" class="form-control w-100" readonly />
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="mb-0" for="formGroupExampleInput2">
                            Área Origen
                        </label>
                        <br />
                        <input type="text" id="areaOrigen" value="Gerencia de T.I." class="form-control w-100" readonly />
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="mb-0"
                               for="formGroupExampleInput2">Usuario Creación</label>
                        <br />
                        <input type="text" id="usuarioRegistro" class="form-control w-100" value="@Session["user_Name"].ToString().Trim() @Session["user_Apellido"].ToString().Trim()" readonly />
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="mb-0" for="formGroupExampleInput2">Área Destino</label><br />
                        @Html.DropDownListFor(x => solicitud.id_Area,
                        new SelectList(solicitud.ListasSolicitud.Areas, "id_Area", "dsc_Area"),
                        "Seleccione Area", new { @class = "form-control w-100" })
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="mb-0" for="formGroupExampleInput2">
                            Tipo de Solicitud
                        </label><br />
                        @Html.DropDownListFor(x => solicitud.id_Tipo_Sol,
                        new SelectList(solicitud.ListasSolicitud.TiposSolicitud, "id_Tipo_Sol", "descripcion"),
                        "Seleccione Tipo de Solicitud", new { @class = "form-control w-100" })
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="mb-0">Prioridad</label><br />
                        @Html.DropDownListFor(x => solicitud.id_Prioridad,
                        new SelectList(solicitud.ListasSolicitud.Prioridades, "id_Prioridad", "dsc_Prioridad"),
                        "Seleccione Prioridad", new { @class = "form-control w-100" })
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-group">
                        <label>Asunto de la soclicitud</label>
                        @Html.TextAreaFor(x => solicitud.asunto_Sol, new { @class = "form-control w-100", @rows = "1" })
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-group">
                        <label for="observaciones">Descripción de la solicitud</label>
                        @Html.TextAreaFor(x => solicitud.detalle_Sol, new { @class = "form-control w-100", @rows = "4" })
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-group row">
                        <label for="Cédula de Identidad"
                               class="col-sm-3 col-form-label">Evidencias para la solicitud</label>
                        <div class="col-sm-9">
                            <section>
                                <input id="files" type="file" multiple>
                                <ul id="preview"></ul>
                            </section>
                        </div>
                    </div>
                </div>

                <div class="col-sm-9">
                </div>
                <div class="col-sm-3">
                    <input type="submit" class="btn btn-primary float-right px-4" value="Modificar Solicitud">
                </div>
            </div>
        </div>
    </div>

}

<script type="text/javascript">

    $(function () {
        $('select').each(function () {
            $(this).select2({
                theme: 'bootstrap4',
                width: $(this).data('width') ? $(this).data('width') : $(this).hasClass('w-100') ? '100%' : 'style',
                placeholder: $(this).data('placeholder'),
                allowClear: Boolean($(this).data('allow-clear')),
                closeOnSelect: !$(this).attr('multiple'),
            });
        });
    });

    $(document).ready(function () {
        $('#solicitud_id_Area').val('@solicitud.id_Area');
        $('#solicitud_id_Area').change();
        $('#solicitud_id_Prioridad').val('@solicitud.id_Prioridad');
        $('#solicitud_id_Prioridad').change();
        $('#solicitud_id_Tipo_Sol').val('@solicitud.id_Tipo_Sol');
        $('#solicitud_id_Tipo_Sol').change();
    });
</script>