SDI_Gestion/Controllers/Reporteria/InformeController.cs
using Newtonsoft.Json;
using SDI_Gestion.Models;
using SDI_Gestion.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SDI_Gestion.Controllers.Reporteria
{
    public class InformeController : BaseController
    {
		List<Object> myModel = new List<object>();
		// GET: Informe
		public ActionResult Index()
        {
			List<DataPoint> dataPoints = new List<DataPoint>();
			List<SDI_Gestion.Models.InformeHH> infoHoras = new List<SDI_Gestion.Models.InformeHH>();


			//Cargamos los meses
			InformeFiltro informeFiltro = new InformeFiltro();
			List<Mes> meses = new List<Mes>();
			List<Ano> anos = new List<Ano>();
			cargaMeses(meses);
			cargaAnos(anos);

			myModel.Add(informeFiltro);
			myModel.Add(meses);
			myModel.Add(anos);
			myModel.Add(infoHoras);
			ViewBag.DataPoints = JsonConvert.SerializeObject(dataPoints);
			return View(myModel);
		}

		// GET: Informe
		public async Task<ActionResult> Cargar(InformeFiltro informeFiltro)
		{

			var httpClient = new HttpClient();
			List<SDI_Gestion.Models.GraficoHH> infoGrafic = new List<SDI_Gestion.Models.GraficoHH>();
			List<SDI_Gestion.Models.InformeHH> infoHoras = new List<SDI_Gestion.Models.InformeHH>();

			//Rescatamos el usuario que esta conectado
			var json = await httpClient.GetStringAsync(Resource.GraficoHHAPIUrl + Session["user_Area"] +"/" + informeFiltro.mes + "/" + informeFiltro.ano);
			infoGrafic = JsonConvert.DeserializeObject<List<GraficoHH>>(json);

			json = await httpClient.GetStringAsync(Resource.InformeHHAPIUrl + Session["user_Area"] +"/" + informeFiltro.mes + "/" + informeFiltro.ano);
			infoHoras = JsonConvert.DeserializeObject<List<InformeHH>>(json);


			List<DataPoint> dataPoints = new List<DataPoint>();
			foreach(var dato in infoGrafic)
            {
				DataPoint dp = new DataPoint(dato.nombre_usuario, dato.total_Horas);
				dataPoints.Add(dp);
            }
			
			
			//Cargamos los meses
			List<Mes> meses = new List<Mes>();
			List<Ano> anos = new List<Ano>();
			cargaMeses(meses);
			cargaAnos(anos);

			myModel.Add(informeFiltro);
			myModel.Add(meses);
			myModel.Add(anos);
			myModel.Add(infoHoras);
			ViewBag.DataPoints = JsonConvert.SerializeObject(dataPoints);
			return View(myModel);
		}

		[HttpGet]
		public async Task<ActionResult> Exportar(int idArea, int ano, int mes)
		{
			var httpClient = new HttpClient();

			var respuesta = await httpClient.GetAsync($"{Resource.InformeHHAPIUrl}Exportar/{idArea}/{mes}/{ano}"); 
			var json = await respuesta.Content.ReadAsStringAsync();

			JsonResult jResult = Json(json, JsonRequestBehavior.AllowGet);
			jResult.MaxJsonLength = int.MaxValue;

			return jResult;
		}

		public void cargaMeses(List<Mes> meses)
		{
			meses.Add(new Mes { Id = 1, Descripcion = "Enero" });
			meses.Add(new Mes { Id = 2, Descripcion = "Febrero" });
			meses.Add(new Mes { Id = 3, Descripcion = "Marzo" });
			meses.Add(new Mes { Id = 4, Descripcion = "Abril" });
			meses.Add(new Mes { Id = 5, Descripcion = "Mayo" });
			meses.Add(new Mes { Id = 6, Descripcion = "Junio" });
			meses.Add(new Mes { Id = 7, Descripcion = "Julio" });
			meses.Add(new Mes { Id = 8, Descripcion = "Agosto" });
			meses.Add(new Mes { Id = 9, Descripcion = "Septiembre" });
			meses.Add(new Mes { Id = 10, Descripcion = "Octubre" });
			meses.Add(new Mes { Id = 11, Descripcion = "Noviembre" });
			meses.Add(new Mes { Id = 12, Descripcion = "Diciembre" });

		}

		public void cargaAnos(List<Ano> anos)
		{
			DateTime fechaActual = DateTime.Today;
			for (int inicio = fechaActual.Year; inicio >= fechaActual.Year -5 ; inicio--)
			{
				anos.Add(new Ano { Id = inicio, Descripcion = inicio.ToString() });
			}

		}

	}
}

SDI_Gestion/Views/Informe/Cargar.cshtml
@using SDI_Gestion.Models
@model IEnumerable<Object>
@{
    InformeFiltro informeFiltro = Model.ToArray()[0] as InformeFiltro;
    List<SDI_Gestion.Models.Mes> meses = Model.ToArray()[1] as List<SDI_Gestion.Models.Mes>;
    List<SDI_Gestion.Models.Ano> anos = Model.ToArray()[2] as List<SDI_Gestion.Models.Ano>;
    List<SDI_Gestion.Models.InformeHH> datosInforme = Model.ToArray()[3] as List<SDI_Gestion.Models.InformeHH>;

    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<link rel="stylesheet" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css">

<script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>

<script type="text/javascript">

    window.onload = function () {
      var chart = new CanvasJS.Chart("chartContainer", {
	animationEnabled: true,
	theme: "light2", // "light1", "light2", "dark1", "dark2"
	title: {
		text: "Horas empleadas en el mes"
	},
	axisY: {
		title: "Número de horas invertidas"
	},
	data: [{
		type: "column",
		dataPoints: @Html.Raw(ViewBag.DataPoints),
	}]
});
chart.render();
    }

     $(document).ready(function (e) {

        $('#tablaUsuarios').DataTable(
                 {
                     "language": {
                         "lengthMenu": "Motrar _MENU_ registros por página",
                         "zeroRecords": "Sin información",
                         "info": "Mostrando página _PAGE_ de _PAGES_",
                         "infoEmpty": "Sin información disponible",
                         "infoFiltered": "(filtered from _MAX_ total records)"
                     }
                 }
        );

        setTimeout(function () {
            $(".content").fadeOut(1500);
        }, 3000);

    });

    function exportar(idArea, mes, ano) {
        $.ajax({
            type: "GET",
            url: `/Informe/Exportar?idArea=` + idArea + `&ano=` + ano + `&mes=` + mes,
            dataType: "json",
            contentType: "application/json; charset=utf-8",

            success: function (response) {
                const blob = base64Toblob(response, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
                guardarArchivo(blob, "InformeHH_" + ano + mes);

            },

            failure: function (response) {
                alert(response.responseText);
            },
            error: function (response) {
                alert(response.responseText);
            }
        });
    }
    function base64Toblob(base64, type = "application/octet-stream") {
        const binStr = window.atob(base64);
        const len = binStr.length;
        const arr = new Uint8Array(len);
        for (let i = 0; i < len; i++) {
            arr[i] = binStr.charCodeAt(i);
        }

        return new Blob([arr], { type: type });

    }
    function guardarArchivo(blob, filename) {
        if (window.navigator.msSaveOrOpenBlob) {
            window.navigator.msSaveOrOpenBlob(blob, filename);
        } else {
            const a = document.createElement('a');
            document.body.appendChild(a);

            const url = window.URL.createObjectURL(blob);
            a.href = url;
            a.download = filename;
            a.click();
            setTimeout(() => {
                window.URL.revokeObjectURL(url);
                document.body.removeChild(a);
            }, 0)
        }
    }

</script>

<div class="row">

    @if (TempData["Mensaje"] != null)
    {

        <div class="col-6 mb-3" style="margin-top:0%;">

            <div class="content" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="col-md-12 alert alert-success">
                    <button type="button" class="close" data-dismiss="toast" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    @TempData["Mensaje"].ToString()
                </div>
            </div>
        </div>
    }
</div>


<div class="card shadow">
    <div class="tab-pane fade show active" id="home" role="tabpanel"
         aria-labelledby="home-tab">

        @using (Html.BeginForm("Cargar", "Informe", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {

            <div class="card-body">
                <div class="row">
                    <div class="col-md-3">
                        <h2>Informe de H.H.</h2>
                    </div>
                </div>
                <hr>

                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="mb-0" for="RUT">Mes</label>
                            <br />
                            @Html.DropDownListFor(x => informeFiltro.mes,
                 new SelectList(meses, "Id", "Descripcion"),
                 "Seleccione Mes", new { @class = "form-control w-100" })
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label class="mb-0" for="formGroupExampleInput2">
                                Año
                            </label>
                            <br />
                            @Html.DropDownListFor(x => informeFiltro.ano,
                 new SelectList(anos, "Id", "Descripcion"),
                 "Seleccione Año", new { @class = "form-control w-100" })
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <br />
                            <input type="submit" class="btn btn-primary float-right px-4" value="Consultar Información">
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="form-group">
                        </div>
                    </div>
                </div>


                <div class="row">
                    <div class="col-6 mt-3">
                        <table id="tablaUsuarios" class="table table-bordered text-dark table-hover">
                            <thead class="thead-light">
                                <tr>
                                    <th>Nombre</th>
                                    <th>Centro de Costo</th>
                                    <th>Cantidad Horas</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var datoInforme in datosInforme)
                                {
                                    <tr>
                                        <td>@datoInforme.nombre_usuario</td>
                                        <td>@datoInforme.area_Descripcion</td>
                                        <td>@datoInforme.total_horas</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>

                    <div class="col-6 mt-3">
                        <div id="chartContainer" style="height: 370px; width: 100%;"></div>
                    </div>


                </div>

                @if (datosInforme.Count > 0)
                {
                    <div class="row">
                        <div class="col-6 mt-3">
                            <a class="mr-2" onclick="return exportar(@Session["user_Area"],@informeFiltro.mes,@informeFiltro.ano);"><i class="bi bi-file-earmark-spreadsheet-fill"></i> Exportar a Excel</a>
                        </div>
                        <div class="col-6 mt-3">

                        </div>

                    </div>

                }
            </div>
        }
        </div>
</div>

SDI_Gestion/Views/Informe/Index.cshtml
@using SDI_Gestion.Models
@model IEnumerable<Object>
@{
    InformeFiltro informeFiltro = Model.ToArray()[0] as InformeFiltro;
    List<SDI_Gestion.Models.Mes> meses = Model.ToArray()[1] as List<SDI_Gestion.Models.Mes>;
    List<SDI_Gestion.Models.Ano> anos = Model.ToArray()[2] as List<SDI_Gestion.Models.Ano>;

    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<link rel="stylesheet" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css">

<script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>

<script type="text/javascript">

    window.onload = function () {
      var chart = new CanvasJS.Chart("chartContainer", {
	animationEnabled: true,
          theme: "light2", // "light1", "light2", "dark1", "dark2"
	title: {
		text: "Horas empleadas en el mes"
	},
	axisY: {
		title: "Número de horas invertidas"
	},
	data: [{
		type: "column",
		dataPoints: @Html.Raw(ViewBag.DataPoints),
	}]
});
chart.render();
    }

    $(document).ready(function (e) {

        $('#tablaUsuarios').DataTable(
            {
                "language": {
                    "lengthMenu": "Motrar _MENU_ registros por página",
                    "zeroRecords": "Sin información",
                    "info": "Mostrando página _PAGE_ de _PAGES_",
                    "infoEmpty": "Sin información disponible",
                    "infoFiltered": "(filtered from _MAX_ total records)"
                }
            }
        );

        setTimeout(function () {
            $(".content").fadeOut(1500);
        }, 3000);

    });
</script>

<div class="row">

    @if (TempData["Mensaje"] != null)
    {

        <div class="col-6 mb-3" style="margin-top:0%;">

            <div class="content" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="col-md-12 alert alert-success">
                    <button type="button" class="close" data-dismiss="toast" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    @TempData["Mensaje"].ToString()
                </div>
            </div>
        </div>
    }
</div>


<div class="card shadow">
    <div class="tab-pane fade show active" id="home" role="tabpanel"
         aria-labelledby="home-tab">

        @using (Html.BeginForm("Cargar", "Informe", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {

            <div class="card-body">
                <div class="row">
                    <div class="col-md-3">
                        <h2>Informe de H.H.</h2>
                    </div>
                </div>
                <hr>

                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="mb-0" for="RUT">Mes</label>
                            <br />
                            @Html.DropDownListFor(x => informeFiltro.mes,
                            new SelectList(meses, "Id", "Descripcion"),
                            "Seleccione Mes", new { @class = "form-control w-100" })
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label class="mb-0" for="formGroupExampleInput2">
                                Año
                            </label>
                            <br />
                            @Html.DropDownListFor(x => informeFiltro.ano,
                            new SelectList(anos, "Id", "Descripcion"),
                            "Seleccione Año", new { @class = "form-control w-100" })
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <br />
                            <input type="submit" class="btn btn-primary float-right px-4" value="Consultar Información">
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="form-group">
                        </div>
                    </div>
                </div>


                <div class="row">
                    <div class="col-6 mt-3">
                        <table id="tablaUsuarios" class="table table-bordered text-dark table-hover">
                            <thead class="thead-light">
                                <tr>
                                    <th>Nombre</th>
                                    <th>Centro de Costo</th>
                                    <th>Cantidad Horas</th>
                                </tr>
                            </thead>
                            <tbody>

                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>

                            </tbody>
                        </table>
                    </div>

                    <div class="col-6 mt-3">
                        <div id="chartContainer" style="height: 370px; width: 100%;"></div>

                    </div>


                </div>
            </div>
        }
    </div>
</div>